/* Uji peramban aplikasi Vue terhadap API sungguhan (Playwright).
 *   Prasyarat: API di :3000 (sudah di-seed) dan `vite preview` di :5173.
 *   node tools/web-e2e.mjs [dir-tangkapan-layar]
 */
import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const out = process.argv[2] || 'dist/shots-web';
mkdirSync(out, { recursive: true });
const PW = process.env.SEED_PASSWORD || 'Rahasia-2026!';
const problems = [];
const ok = (c, label, extra) => { if (c) console.log('  ✓ ' + label); else { problems.push(label); console.log('  ✗ ' + label, extra ?? ''); } };
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 960 } });
const page = await ctx.newPage();
page.on('pageerror', (e) => { problems.push('pageerror: ' + e.message); console.log('  ! pageerror', page.url(), (e.stack ?? '').split('\n').slice(0, 4).join(' | ')); });
page.on('console', (m) => { if (m.type() === 'error' && !/40[13]|422|Failed to load resource/.test(m.text())) problems.push('console: ' + m.text()); });
const base = 'http://localhost:5173';
let ipSeq = 0;
const login = async (email) => {
  /* Batas laju login per IP: tiap login memakai alamat berbeda (API di belakang proksi tepercaya). */
  await page.setExtraHTTPHeaders({ 'X-Forwarded-For': `10.88.${Date.now() % 200}.${(ipSeq += 1) % 250 + 1}` });
  await page.goto(base + '/masuk'); await page.waitForSelector('#email');
  await page.fill('#email', email); await page.fill('#password', PW); await page.click('button[type=submit]');
  await page.waitForURL((u) => !u.pathname.startsWith('/masuk'), { timeout: 15000 }); await page.waitForTimeout(600);
};
const shot = (n) => page.screenshot({ path: `${out}/${n}.png` });

console.log('Masuk & dasbor');
await page.goto(base + '/masuk'); await shot('01-masuk');
await login('andi@knm.co.id');
ok(await page.locator('.kpi-tile').count() >= 4, 'dasbor memuat ubin KPI dari API'); await shot('02-dasbor');
ok((await page.locator('.contextbar').innerText()).includes('Semua cabang'), 'akuntan senior mulai pada konteks semua cabang');

console.log('Laporan');
for (const [path, name, check] of [
  ['/jurnal', '03-jurnal', 'tbody tr[data-row]'], ['/buku-besar', '04-buku-besar', '.table.report tbody tr'], ['/neraca-saldo', '05-neraca-saldo', '.pill[data-tone=ok]'],
  ['/laba-rugi', '06-laba-rugi', '.report-stmt'], ['/neraca', '07-neraca', '.report-stmt'], ['/konsolidasi', '08-konsolidasi', '.report-stmt'],
  ['/integrasi', '09-integrasi', '.pill'], ['/cabang', '10-cabang', '.branch-card'], ['/bagan-akun', '11-bagan-akun', '.coa-summary'], ['/kas-bank', '12-kas-bank', 'tbody tr'], ['/jejak-audit', '13-jejak-audit', 'tbody tr'],
]) {
  await page.goto(base + path); await page.waitForSelector(check, { timeout: 15000 }).catch(() => null); await page.waitForTimeout(400);
  ok(await page.locator(check).count() > 0, `${path} dirender dengan data`); await shot(name);
}
await page.goto(base + '/integrasi'); await page.waitForSelector('.pill');
ok(await page.locator('.pill[data-tone=danger]').count() === 0, 'tidak ada selisih rekonsiliasi');
await page.goto(base + '/neraca'); await page.waitForSelector('.report-stmt');
const bsCodes = await page.locator('.report-stmt .code').allInnerTexts();
ok(bsCodes.map((c) => c.trim()).includes('1-1100') && bsCodes.every((c) => /^\d-\d\d00$/.test(c.trim())), 'neraca menampilkan header level 3 (mis. 1-1100 Bank), bukan akun detail', bsCodes.slice(0, 8));
ok((await page.locator('.kpi-tile .pill').innerText()).includes('Aset = Liabilitas'), 'neraca konsolidasi seimbang');

console.log('Konteks cabang');
await page.click('.contextbar [data-action="switch-branch"]'); await page.click('[data-set-branch="CKR"]'); await page.waitForTimeout(700);
ok((await page.locator('.contextbar').innerText()).includes('Cikarang'), 'pemilih cabang mengubah konteks');
await page.waitForSelector('.report-stmt'); await shot('14-neraca-cikarang');
ok((await page.locator('.kpi-tile .pill').innerText()).includes('Aset = Liabilitas'), 'neraca cabang Cikarang seimbang');
await page.click('.contextbar [data-action="switch-period"]'); await page.click('[data-set-period="2026"]'); await page.waitForTimeout(700);
ok((await page.locator('.contextbar').innerText()).includes('TA 2026'), 'pemilih periode mengubah konteks');
await page.click('.contextbar [data-action="switch-branch"]'); await page.click('[data-set-branch="ALL"]'); await page.waitForTimeout(300);
await page.click('.contextbar [data-action="switch-period"]'); await page.click('[data-set-period="2026-08"]'); await page.waitForTimeout(300);

console.log('Jurnal: laci & buku besar');
await page.goto(base + '/jurnal'); await page.waitForSelector('tbody tr[data-row]');
await page.click('tbody tr[data-row]'); await page.waitForSelector('.drawer .table');
ok(await page.locator('.drawer .table tbody tr').count() >= 2, 'laci jurnal menampilkan baris debit/kredit'); await shot('15-jurnal-laci');
await page.click('.drawer [data-gl]'); await page.waitForURL(/buku-besar/); await page.waitForSelector('.table.report');
ok(page.url().includes('buku-besar'), 'tautan baris jurnal membuka kartu buku besar');

console.log('Alur memorial: staf membuat, akuntan memposting');
await page.click('.topbar-user button'); await page.click('.user-menu .menu-item:has-text("Keluar")'); await page.waitForURL(/masuk/);
await login('sari@knm.co.id');
await page.goto(base + '/jurnal'); await page.waitForSelector('[data-action="new-journal"]');
await page.click('[data-action="new-journal"]'); await page.waitForSelector('#jv-body');
await page.fill('#jv-desc', 'Uji peramban: perlengkapan kantor dari kas kecil');
await page.selectOption('#jv-branch', 'JKT');
await page.waitForSelector('#jv-body tr:nth-child(1) [data-jv-acc] option[value="5-3701"]', { state: 'attached' });
ok(await page.locator('#jv-body tr:nth-child(1) [data-jv-acc] option[value="1-1100"], #jv-body tr:nth-child(1) [data-jv-acc] option[value="5-3700"]').count() === 0, 'formulir jurnal hanya menawarkan akun detail (tanpa header)');
await page.selectOption('#jv-body tr:nth-child(1) [data-jv-acc]', '5-3701'); await page.fill('#jv-body tr:nth-child(1) [data-jv-debit]', '175000');
const kasJkt = await page.locator('#jv-body tr:nth-child(2) [data-jv-acc] option', { hasText: 'Kas Kecil — Jakarta' }).getAttribute('value');
ok(/^1-12\d\d$/.test(kasJkt ?? ''), 'kas kecil Jakarta adalah akun detail di bawah header Kas', kasJkt);
await page.selectOption('#jv-body tr:nth-child(2) [data-jv-acc]', kasJkt); await page.fill('#jv-body tr:nth-child(2) [data-jv-credit]', '175000');
await shot('16-jurnal-modal');
await page.click('[data-action="submit-journal"]'); await page.waitForSelector('.toast', { timeout: 10000 });
const t1 = await page.locator('.toast').last().innerText();
ok(/persetujuan/.test(t1), 'staf keuangan mengirim jurnal untuk persetujuan', t1);
await page.click('.chip:has-text("Menunggu")'); await page.waitForTimeout(500);
await page.click('tbody tr[data-row]'); await page.waitForSelector('.drawer');
ok(await page.locator('.drawer [data-action="post-journal"]').count() === 0, 'pembuat tidak melihat tombol posting');
await page.keyboard.press('Escape');
await page.click('.topbar-user button'); await page.click('.user-menu .menu-item:has-text("Keluar")'); await page.waitForURL(/masuk/);
await login('andi@knm.co.id');
await page.goto(base + '/jurnal?status=pending'); await page.waitForSelector('tbody tr[data-row]');
await page.click('tbody tr[data-row]:has-text("Uji peramban")'); await page.waitForSelector('.drawer [data-action="post-journal"]');
await page.click('.drawer [data-action="post-journal"]'); await page.waitForSelector('.toast');
const t2 = await page.locator('.toast').last().innerText();
ok(/diposting/.test(t2), 'akuntan senior memposting jurnal staf', t2);
await page.goto(base + '/integrasi'); await page.waitForSelector('.pill'); await page.waitForTimeout(500);
ok(await page.locator('.pill[data-tone=danger]').count() === 0, 'rekonsiliasi tetap cocok setelah posting lewat UI');

console.log('Asisten AI');
ok((await page.locator('.rail-link-text').allInnerTexts()).includes('Asisten AI'), 'menu Asisten AI tampil bagi akuntan senior');
await page.goto(base + '/asisten'); await page.waitForSelector('.empty-title, .assistant', { timeout: 15000 });
ok((await page.locator('.empty-title').innerText().catch(() => '')).includes('belum diaktifkan'), 'tanpa kunci API halaman asisten menjelaskan cara mengaktifkan');
/* Respons asisten dicegat: menguji tampilan tanpa memanggil Claude API. */
const chatBodies = [];
const REPLY = [
  '**Laba bersih** periode Agustus 2026 per cabang:',
  '',
  '| Cabang | Pendapatan | Laba bersih | Margin |',
  '| --- | ---: | ---: | ---: |',
  '| Jakarta | Rp 1.250.000.000 | Rp 180.000.000 | 14,4% |',
  '| Surabaya | Rp 640.000.000 | Rp 52.000.000 | 8,1% |',
  '',
  '- Margin Surabaya paling rendah.',
  '- Uraian jurnal berisi <img src=x onerror="window.__xss=1"> tetap tampil sebagai teks.',
].join('\n');
await page.route('**/api/v1/assistant/status', (r) => r.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ enabled: true, model: 'claude-opus-5' }) }));
await page.route('**/api/v1/assistant/chat', async (r) => {
  chatBodies.push(JSON.parse(r.request().postData() || '{}'));
  await new Promise((res) => setTimeout(res, 400));
  await r.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ reply: REPLY, toolsUsed: [{ name: 'konsolidasi', ok: true }, { name: 'laba_rugi', ok: true }], usage: { inputTokens: 1, outputTokens: 1 }, model: 'claude-opus-5', stopReason: 'end_turn' }) });
});
await page.reload(); await page.waitForSelector('.assistant-suggest .chip', { timeout: 15000 });
await page.click('.assistant-suggest .chip >> nth=0');
await page.waitForSelector('.assistant-typing', { timeout: 5000 }).catch(() => null);
await page.waitForSelector('.assistant-msg.is-assistant .md table', { timeout: 15000 });
ok(chatBodies[0]?.messages?.length === 1 && chatBodies[0].messages[0].role === 'user', 'pertanyaan pertama dikirim tanpa riwayat', chatBodies[0]);
ok(await page.locator('.assistant-msg.is-assistant .md table tbody tr').count() === 2, 'tabel Markdown jawaban dirender sebagai tabel');
ok(await page.locator('.md td.ta-r.num').count() >= 6, 'kolom angka rata kanan');
ok(await page.locator('.md img').count() === 0 && !(await page.evaluate(() => window.__xss)) && (await page.locator('.md').innerText()).includes('<img'), 'HTML di jawaban di-escape (tanpa XSS)');
ok((await page.locator('.assistant-tools').innerText()).includes('Konsolidasi'), 'sumber data yang dibaca asisten ditampilkan');
await page.fill('#assistant-input', 'Kenapa margin Surabaya rendah?'); await page.press('#assistant-input', 'Enter');
await page.waitForFunction(() => document.querySelectorAll('.assistant-msg.is-assistant .md').length === 2, null, { timeout: 15000 });
ok(chatBodies[1]?.messages?.length === 3 && chatBodies[1].messages.map((m) => m.role).join() === 'user,assistant,user', 'pertanyaan lanjutan membawa riwayat tanya-jawab', chatBodies[1]?.messages?.map((m) => m.role));
await shot('19-asisten');
await page.unroute('**/api/v1/assistant/status'); await page.unroute('**/api/v1/assistant/chat');


console.log('Paginasi tabel');
for (const path of ['/jurnal', '/buku-besar', '/neraca-saldo', '/bagan-akun', '/kas-bank', '/periode', '/integrasi', '/konsolidasi', '/dasbor', '/jejak-audit']) {
  await page.goto(base + path); await page.waitForSelector('.pager-bar', { timeout: 15000 }).catch(() => null);
  const info = await page.locator('[data-pager-info]').first().innerText().catch(() => '');
  ok(/Menampilkan \d/.test(info), `${path} memiliki paginasi`, info);
}
await page.goto(base + '/jurnal'); await page.waitForSelector('tbody tr[data-row]');
const firstNo = await page.locator('tbody tr[data-row] td').first().innerText();
await page.click('[data-pager-next]'); await page.waitForFunction((n) => document.querySelector('tbody tr[data-row] td')?.textContent !== n, firstNo, { timeout: 10000 });
ok((await page.locator('[data-pager-info]').innerText()).startsWith('Menampilkan 26–'), 'jurnal pindah ke halaman 2');
await page.selectOption('.pager-size select', '10'); await page.waitForTimeout(800);
ok(await page.locator('tbody tr[data-row]').count() === 10 && (await page.locator('[data-pager-info]').innerText()).startsWith('Menampilkan 1–10'), 'ukuran halaman jurnal dapat diubah');
await page.goto(base + '/bagan-akun'); await page.waitForSelector('[data-table=accounts] tbody tr');
await page.fill('[data-filter=account]', 'kas'); await page.waitForTimeout(300);
ok((await page.locator('[data-table=accounts] tbody tr').allInnerTexts()).every((t) => /kas/i.test(t)), 'pencarian bagan akun menyaring baris');

console.log('CRUD lewat antarmuka (admin)');
await page.click('.topbar-user button'); await page.click('.user-menu .menu-item:has-text("Keluar")'); await page.waitForURL(/masuk/);
await login('admin@knm.co.id');
const accCode = `5-37${String(Date.now() % 90 + 10)}`;
await page.goto(base + '/bagan-akun'); await page.waitForSelector('[data-action=new-account]');
await page.click('[data-action=new-account]'); await page.fill('#acc-code', '5-3800'); await page.waitForTimeout(150);
ok(await page.locator('#acc-type').isDisabled() && await page.inputValue('#acc-type') === 'header', 'kode level 3 memaksa tipe header');
await page.fill('#acc-code', accCode); await page.selectOption('#acc-type', 'detail'); await page.waitForTimeout(150);
ok((await page.locator('[data-code-info]').innerText()).includes('Level 4 · induk 5-3700'), 'induk & level ditampilkan dari pola kode', await page.locator('[data-code-info]').innerText()); await page.fill('#acc-name', 'Beban Uji Peramban'); await page.click('[data-action=save-account]');
await page.waitForSelector('.toast'); await page.fill('[data-filter=account]', accCode); await page.waitForTimeout(400);
ok(await page.locator(`[data-account="${accCode}"]`).count() === 1, 'akun baru dibuat lewat formulir');
await page.click(`[data-account="${accCode}"] [data-action=edit-account]`); await page.fill('#acc-name', 'Beban Uji Peramban Diubah'); await page.click('[data-action=save-account]');
await page.waitForFunction((c) => document.querySelector(`[data-account="${c}"]`)?.textContent?.includes('Diubah'), accCode, { timeout: 10000 });
ok(true, 'nama akun diubah lewat formulir');
await page.click(`[data-account="${accCode}"] [data-action=toggle-account]`); await page.fill('#reason-input', 'uji nonaktif peramban'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction((c) => [...document.querySelectorAll(`[data-account="${c}"] .pill`)].some((p) => p.textContent?.trim() === 'Nonaktif'), accCode, { timeout: 10000 });
ok(true, 'akun dinonaktifkan dengan alasan');
await page.click(`[data-account="${accCode}"] [data-action=delete-account]`); await page.fill('#reason-input', 'uji hapus peramban'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction((c) => !document.querySelector(`[data-account="${c}"]`), accCode, { timeout: 10000 });
ok(true, 'akun dihapus lewat konfirmasi');
await page.fill('[data-filter=account]', '1-1301'); await page.waitForTimeout(300);
ok(await page.locator('[data-account="1-1301"] [data-action=delete-account]').count() === 0 && (await page.locator('[data-account="1-1301"]').innerText()).includes('Pemetaan'), 'akun tertaut (piutang usaha) tidak menampilkan tombol hapus');
await page.fill('[data-filter=account]', ''); await page.selectOption('[data-filter=type]', 'header'); await page.waitForTimeout(300);
ok((await page.locator('[data-table=accounts] tbody tr[data-account]').allInnerTexts()).every((t) => t.includes('Header')), 'saringan header menampilkan akun level 1–3');
await shot('23-bagan-akun');

const bCode = `BNK-SBY-W${String(Date.now() % 1000)}`;
await page.goto(base + '/kas-bank'); await page.waitForSelector('[data-action=new-bank]');
await page.click('[data-action=new-bank]'); await page.selectOption('#bank-branch', 'SBY'); await page.fill('#bank-code', bCode);
await page.fill('#bank-name', 'BRI — Rekening Uji Peramban'); await page.fill('#bank-bank', 'BRI'); await page.fill('#bank-last4', '5566'); await page.click('[data-action=save-bank]');
await page.waitForSelector('.toast'); await page.fill('[data-filter=bank]', bCode); await page.waitForTimeout(400);
ok((await page.locator(`[data-bank="${bCode}"]`).innerText().catch(() => '')).includes('••••5566'), 'rekening baru dibuat lewat formulir');
await page.click(`[data-bank="${bCode}"] [data-action=edit-bank]`); await page.fill('#bank-name', 'BRI — Rekening Uji Diubah'); await page.click('[data-action=save-bank]');
await page.waitForFunction((c) => document.querySelector(`[data-bank="${c}"]`)?.textContent?.includes('Diubah'), bCode, { timeout: 10000 });
ok(true, 'rekening diubah lewat formulir');
await page.click(`[data-bank="${bCode}"] [data-action=delete-bank]`); await page.fill('#reason-input', 'uji hapus rekening'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction((c) => !document.querySelector(`[data-bank="${c}"]`), bCode, { timeout: 10000 });
ok(true, 'rekening dihapus lewat konfirmasi');

await page.goto(base + '/cabang'); await page.waitForSelector('[data-branch-card=SBY]');
await page.click('[data-branch-card=SBY] [data-action=edit-branch]'); await page.fill('#br-phone', '031-777-0000'); await page.click('[data-action=submit-branch]');
await page.waitForSelector('.toast'); await page.waitForTimeout(500);
ok((await page.locator('.toast').last().innerText()).includes('Cabang diperbarui') && !(await page.locator('.modal').count()), 'data cabang diubah lewat formulir');
await page.click('[data-branch-card=SBY] [data-action=toggle-branch]'); await page.fill('#reason-input', 'uji nonaktif cabang'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction(() => document.querySelector('[data-branch-card=SBY] .pill')?.textContent?.trim() === 'Nonaktif', null, { timeout: 10000 });
await page.click('[data-branch-card=SBY] [data-action=toggle-branch]'); await page.fill('#reason-input', 'uji aktifkan cabang'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction(() => document.querySelector('[data-branch-card=SBY] .pill')?.textContent?.trim() === 'Aktif', null, { timeout: 10000 });
ok(true, 'cabang dinonaktifkan lalu diaktifkan kembali dengan alasan (tanpa prompt peramban)');
await shot('21-crud-admin');

console.log('Periode fiskal');
await page.click('.topbar-user button'); await page.click('.user-menu .menu-item:has-text("Keluar")'); await page.waitForURL(/masuk/);
await login('andi@knm.co.id');
await page.goto(base + '/periode'); await page.waitForSelector('[data-period="2026-11"]');
await page.click('[data-period="2026-11"] [data-action=close-period]'); await page.fill('#reason-input', 'uji tutup periode'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction(() => document.querySelector('[data-period="2026-11"] .pill')?.textContent?.trim() === 'Ditutup', null, { timeout: 15000 });
ok(await page.locator('[data-period="2026-11"] [data-action=reopen-period]').count() === 0, 'akuntan menutup periode; tombol buka kembali tidak tersedia baginya');
await shot('22-periode');
await page.click('.topbar-user button'); await page.click('.user-menu .menu-item:has-text("Keluar")'); await page.waitForURL(/masuk/);
await login('admin@knm.co.id');
await page.goto(base + '/periode'); await page.waitForSelector('[data-period="2026-11"] [data-action=reopen-period]');
await page.click('[data-period="2026-11"] [data-action=reopen-period]'); await page.fill('#reason-input', 'uji buka periode'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction(() => document.querySelector('[data-period="2026-11"] .pill')?.textContent?.trim() === 'Terbuka', null, { timeout: 15000 });
ok(true, 'admin membuka kembali periode');

console.log('Pengguna, peran & pengaturan (admin)');
const logout = async () => { await page.click('.topbar-user button'); await page.click('.user-menu .menu-item:has-text("Keluar")'); await page.waitForURL(/masuk/); };
await page.goto(base + '/pengguna'); await page.waitForSelector('[data-table=users] tbody tr[data-user]');
ok(await page.locator('[data-user="andi@knm.co.id"]').count() === 1, 'daftar pengguna memuat akun dari API'); await shot('30-pengguna');
const newEmail = `uji.web.${Date.now()}@knm.co.id`;
await page.click('[data-action=new-user]'); await page.fill('#user-name', 'Uji Peramban'); await page.fill('#user-email', newEmail);
await page.selectOption('[data-assignment] [data-field=role]', 'staf_keuangan'); await page.selectOption('[data-assignment] [data-field=branch]', 'ALL');
await shot('31-pengguna-baru'); await page.click('[data-action=save-user]');
await page.waitForSelector('[data-temp-password]'); const tempPw = (await page.locator('[data-temp-password]').innerText()).trim();
ok(/^[A-Za-z]{4}-\d{4}-[A-Za-z]{4}$/.test(tempPw), 'kata sandi sementara ditampilkan sekali', tempPw); await shot('32-sandi-sementara');
await page.click('[data-action=close-temp]');
await page.fill('[data-filter=user]', newEmail); await page.waitForSelector(`[data-user="${newEmail}"]`);
ok((await page.locator(`[data-user="${newEmail}"] .pill`).allInnerTexts()).some((t) => t.includes('Kata sandi sementara')), 'pengguna baru ditandai wajib ganti kata sandi');
await page.click(`[data-user="${newEmail}"] [data-action=edit-user]`); await page.fill('#user-name', 'Uji Peramban Ubah'); await page.fill('#user-reason', 'uji ubah nama');
await page.click('[data-action=save-user]'); await page.waitForFunction((e) => document.querySelector(`[data-user="${e}"] .cell-strong`)?.textContent?.includes('Ubah'), newEmail, { timeout: 10000 });
ok(true, 'ubah pengguna tersimpan');
await page.fill('[data-filter=user]', 'uji peramban'); await page.waitForTimeout(200);
ok(await page.locator('[data-table=users] tbody tr[data-user]').count() >= 1, 'pencarian pengguna menyaring tabel');

await page.goto(base + '/peran'); await page.waitForSelector('[data-table=matrix] .perm');
ok(await page.locator('[data-table=matrix] .perm').count() >= 28 * 5, 'matriks peran × izin dirender'); await shot('33-peran');
const cell = '[data-cell="gudang:report.export"]';
const before = await page.getAttribute(cell, 'aria-pressed');
await page.click(cell); ok(await page.getAttribute(cell, 'data-level') === 'read', 'sel yang diubah ditandai belum disimpan');
await page.click('[data-action=save-matrix]'); await page.fill('#reason-input', 'uji matriks izin'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction(([c, b]) => document.querySelector(c)?.getAttribute('data-level') !== 'read' && document.querySelector(c)?.getAttribute('aria-pressed') !== b, [cell, before], { timeout: 10000 });
ok(true, 'perubahan matriks tersimpan ke server');
await page.click(cell); await page.click('[data-action=save-matrix]'); await page.fill('#reason-input', 'kembalikan uji'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction(([c, b]) => document.querySelector(c)?.getAttribute('aria-pressed') === b && document.querySelector(c)?.getAttribute('data-level') !== 'read', [cell, before], { timeout: 10000 });
await page.click('[data-cell="akuntan_senior:ledger.period.reopen"]');
ok(await page.locator('[data-sod-warning]').count() === 1 && await page.locator('[data-action=save-matrix]').isDisabled(), 'pelanggaran pemisahan tugas diperingatkan & simpan diblokir'); await shot('34-peran-sod');
await page.click('[data-action=discard-matrix]');

await page.goto(base + '/pengaturan'); await page.waitForSelector('#set-phone');
const phone0 = await page.inputValue('#set-phone');
await page.fill('#set-phone', '(021) 555-0199'); await page.click('[data-action=save-settings]'); await page.waitForTimeout(800);
await page.reload(); await page.waitForSelector('#set-phone'); await page.waitForTimeout(300);
ok(await page.inputValue('#set-phone') === '(021) 555-0199', 'pengaturan perusahaan tersimpan'); await shot('35-pengaturan');
await page.fill('#set-phone', phone0); await page.click('[data-action=save-settings]'); await page.waitForTimeout(600);

await logout();
await page.goto(base + '/masuk'); await page.fill('#email', newEmail); await page.fill('#password', tempPw); await page.click('button[type=submit]');
await page.waitForURL(/\/profil/, { timeout: 15000 }); await page.waitForSelector('[data-forced-change]');
ok(true, 'pengguna dengan kata sandi sementara diarahkan ke Profil'); await shot('36-wajib-ganti');
await page.goto(base + '/jurnal'); await page.waitForTimeout(600);
ok(page.url().includes('/profil'), 'menu lain terkunci sebelum kata sandi diganti');
await page.fill('#pw-current', tempPw); await page.fill('#pw-new', 'pendek'); await page.waitForTimeout(100);
ok(await page.locator('.field-hint.neg').count() >= 1, 'petunjuk kebijakan kata sandi tampil');
await page.fill('#pw-new', 'Kuat-Sekali-2026x'); await page.fill('#pw-confirm', 'Kuat-Sekali-2026x'); await page.click('[data-action=change-password]');
await page.waitForURL(/\/(dasbor|jurnal)/, { timeout: 15000 });
ok(true, 'ganti kata sandi membuka akses aplikasi');
await page.goto(base + '/profil'); await page.waitForSelector('[data-table=sessions] tbody tr');
ok((await page.locator('[data-table=sessions]').innerText()).includes('Sesi ini'), 'daftar sesi aktif menandai sesi ini'); await shot('37-profil');
await logout(); await login('admin@knm.co.id');
await page.goto(base + '/pengguna'); await page.waitForSelector('[data-filter=user]'); await page.fill('[data-filter=user]', newEmail); await page.waitForSelector(`[data-user="${newEmail}"]`);
await page.click(`[data-user="${newEmail}"] [data-action=toggle-user]`); await page.fill('#reason-input', 'bersihkan akun uji'); await page.click('[data-action=confirm-reason]');
await page.waitForFunction((e) => [...document.querySelectorAll(`[data-user="${e}"] .pill`)].some((p) => p.textContent.trim() === 'Nonaktif'), newEmail, { timeout: 10000 });
ok(true, 'akun uji dinonaktifkan');

console.log('Penjualan & piutang');
const salesCtx = async (branch) => {
  await page.click('.contextbar [data-action="switch-branch"]'); await page.click(`[data-set-branch="${branch}"]`); await page.waitForTimeout(300);
  await page.click('.contextbar [data-action="switch-period"]'); await page.click('[data-set-period="2026-09"]'); await page.waitForTimeout(300);
};
await logout(); await login('sari@knm.co.id'); await salesCtx('CKR');
await page.goto(base + '/pesanan-penjualan'); await page.waitForSelector('[data-table=orders] tbody tr[data-row]');
ok(await page.locator('[data-table=orders] tbody tr[data-row]').count() > 0, 'daftar pesanan penjualan dimuat'); await shot('40-pesanan');
await page.click('[data-action=new-order]'); await page.waitForSelector('#doc-customer option:nth-child(3)', { state: 'attached' });
const custVal = await page.locator('#doc-customer option', { hasText: 'PT Global Komponen Indo' }).getAttribute('value');
await page.selectOption('#doc-customer', custVal);
const braketVal = await page.locator('[data-line] [data-field=product] option', { hasText: 'BRG-1108' }).first().getAttribute('value');
await page.selectOption('[data-line] [data-field=product]', braketVal); await page.fill('[data-line] [data-field=qty]', '4');
await page.click('[data-action=add-line]'); await page.fill('[data-line] >> nth=1 >> [data-field=description]', 'Jasa pengiriman khusus'); await page.fill('[data-line] >> nth=1 >> [data-field=price]', '750000');
const expected = Math.round((4 * 385000 + 750000) * 1.11);
ok((await page.locator('[data-total]').innerText()).replace(/\D/g, '') === String(expected), 'pratinjau total (DPP + PPN 11%) dihitung di formulir', await page.locator('[data-total]').innerText());
await shot('41-pesanan-baru'); await page.click('[data-action=submit-order]');
await page.waitForSelector('.drawer [data-credit]'); await page.waitForTimeout(300);
const soNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
ok(/^SO-2026-\d{4}$/.test(soNo) && (await page.locator('.drawer .drawer-eyebrow .pill').innerText()).includes('Disetujui'), 'pesanan diajukan & disetujui otomatis (lolos plafon)', soNo);
await page.click('[data-action=order-to-invoice]'); await page.waitForURL(/\/faktur\?id=/); await page.waitForSelector('.drawer [data-open]');
const invNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
ok(/^INV-2026-\d{4}$/.test(invNo) && (await page.locator('.drawer .drawer-eyebrow .pill').innerText()).includes('Draf'), 'pesanan menjadi draf faktur', invNo);
ok(await page.locator('[data-action=issue-invoice]').count() === 0, 'pembuat faktur tidak ditawari tombol terbitkan (SoD)');
await shot('42-faktur-draf');
await page.keyboard.press('Escape'); await logout(); await login('andi@knm.co.id'); await salesCtx('CKR');
await page.goto(base + '/faktur'); await page.waitForSelector(`[data-invoice="${invNo}"]`); await page.click(`[data-invoice="${invNo}"]`);
await page.waitForSelector('[data-action=issue-invoice]'); await page.click('[data-action=issue-invoice]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Belum dibayar'), null, { timeout: 15000 });
ok(await page.locator('[data-table=invoice-journals] tbody tr').count() === 2, 'faktur terbit: jurnal penjualan & HPP tampil di laci'); await shot('43-faktur-terbit');
await page.keyboard.press('Escape'); await logout(); await login('sari@knm.co.id'); await salesCtx('CKR');
await page.goto(base + `/faktur`); await page.waitForSelector(`[data-invoice="${invNo}"]`); await page.click(`[data-invoice="${invNo}"]`);
await page.waitForSelector('[data-action=new-receipt]'); await page.click('[data-action=new-receipt]'); await page.waitForSelector('#rc-amount');
await page.fill('#rc-amount', '1000000'); await page.fill('#rc-ref', 'TRF-UJI'); await page.click('[data-action=save-receipt]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('sebagian'), null, { timeout: 15000 });
ok((await page.locator('[data-table=receipts] tbody tr').count()) === 1, 'penerimaan sebagian tercatat'); await shot('44-penerimaan');
await page.keyboard.press('Escape');
await page.goto(base + '/piutang'); await page.waitForSelector('[data-aging]');
ok((await page.locator('[data-aging]').innerText()).includes('Cocok'), 'piutang usaha cocok dengan buku besar'); await shot('45-piutang');
/* Ember pertama yang berisi faktur (isi ember bergantung pada tanggal hari ini). */
const filledBucket = page.locator('[data-bucket]').filter({ hasNotText: /(^|\D)0 faktur/ }).first();
await filledBucket.click(); await page.waitForTimeout(200);
ok(await page.locator('[data-table=ar-invoices] tbody tr[data-row]').count() >= 1, 'ember umur piutang menyaring faktur');
await page.goto(base + '/pelanggan'); await page.waitForSelector('[data-table=customers] tbody tr[data-row]');
ok(await page.locator('[data-action=new-customer]').count() === 0, 'staf tidak dapat menambah pelanggan (tombol tersembunyi)'); await shot('46-pelanggan');
await page.goto(base + '/produk'); await page.waitForSelector('[data-product="BRG-1108"]');
ok((await page.locator('[data-product="BRG-1108"]').innerText()).includes('CKR'), 'produk menampilkan stok per cabang');
await page.goto(base + '/integrasi'); await page.waitForSelector('.pill');
ok(await page.locator('.pill[data-tone=danger]').count() === 0, 'integrasi Sep 2026 cocok setelah transaksi penjualan');
await logout(); await login('osmond@knm.co.id');
await page.goto(base + '/pesanan-penjualan'); await page.waitForSelector('[data-chip=menunggu]'); await page.click('[data-chip=menunggu]');
if (await page.locator('[data-table=orders] tbody tr[data-row]').count()) {
  await page.click('[data-table=orders] tbody tr[data-row] >> nth=0'); await page.waitForSelector('[data-decision]');
  ok(await page.locator('[data-action=approve-order]').count() === 1, 'manajer melihat panel keputusan & tombol setujui'); await shot('47-keputusan');
  await page.keyboard.press('Escape');
}
await logout(); await login('admin@knm.co.id');

console.log('Pembelian & hutang');
await logout(); await login('sari@knm.co.id'); await salesCtx('SBY');
await page.goto(base + '/pesanan-pembelian'); await page.waitForSelector('[data-table=purchase-orders] tbody tr[data-row]');
ok(await page.locator('[data-table=purchase-orders] tbody tr[data-row]').count() > 0, 'daftar pesanan pembelian dimuat'); await shot('50-po');
await page.click('[data-action=new-po]'); await page.waitForSelector('#pd-supplier option:nth-child(3)', { state: 'attached' });
await page.selectOption('#pd-supplier', await page.locator('#pd-supplier option', { hasText: 'PT Kabel Cipta Sarana' }).getAttribute('value'));
await page.waitForSelector('[data-line] [data-field=product] option >> text=BRG-3390', { state: 'attached' });
await page.selectOption('[data-line] [data-field=product]', await page.locator('[data-line] [data-field=product] option', { hasText: 'BRG-3390' }).first().getAttribute('value'));
await page.fill('[data-line] [data-field=qty]', '200'); await page.fill('[data-line] [data-field=price]', '35000');
await page.click('[data-action=add-line]'); await page.fill('[data-line] >> nth=1 >> [data-field=description]', 'Ongkos angkut Surabaya');
await page.selectOption('[data-line] >> nth=1 >> [data-field=account]', '5-2401'); await page.fill('[data-line] >> nth=1 >> [data-field=price]', '500000');
ok((await page.locator('[data-total]').innerText()).replace(/\D/g, '') === String(Math.round((200 * 35000 + 500000) * 1.11)), 'pratinjau total PO (DPP + PPN masukan 11%)', await page.locator('[data-total]').innerText());
await shot('51-po-baru'); await page.click('[data-action=submit-po]');
await page.waitForSelector('.drawer [data-table=po-lines]'); await page.waitForTimeout(300);
const poNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
ok(/^PO-2026-\d{4}$/.test(poNo) && (await page.locator('.drawer .drawer-eyebrow .pill').innerText()).includes('Disetujui'), 'PO di bawah ambang disetujui otomatis', poNo);
ok(await page.locator('[data-action=receive-po]').count() === 0, 'staf keuangan tidak ditawari tombol terima barang');
await page.keyboard.press('Escape'); await logout(); await login('fitri@knm.co.id');
const navG = await page.locator('.rail-link-text').allInnerTexts();
ok(navG.includes('Penerimaan Barang') && !navG.includes('Tagihan Pemasok') && !navG.includes('Pembayaran'), 'staf gudang melihat penerimaan barang, bukan tagihan/pembayaran', navG);
await page.goto(base + '/penerimaan-barang'); await page.waitForSelector(`[data-table=incoming] [data-po="${poNo}"]`); await shot('52-penerimaan');
await page.click(`[data-table=incoming] [data-po="${poNo}"]`); await page.waitForSelector('[data-action=receive-po]'); await page.click('[data-action=receive-po]');
await page.waitForSelector('[data-field=receive-qty]');
ok((await page.locator('[data-receive-value]').innerText()).replace(/\D/g, '') === '7000000', 'nilai penerimaan = qty × harga PO', await page.locator('[data-receive-value]').innerText());
await page.click('[data-action=save-receipt]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Diterima sebagian'), null, { timeout: 15000 });
ok(await page.locator('.drawer [data-table=po-receipts] tbody tr').count() === 1 && await page.locator('.drawer [data-uninvoiced]').count() === 1, 'penerimaan tercatat; barang diterima menunggu tagihan'); await shot('53-diterima');
ok(await page.locator('[data-action=po-to-invoice]').count() === 0, 'gudang tidak ditawari pembuatan tagihan');
await page.keyboard.press('Escape'); await logout(); await login('sari@knm.co.id'); await salesCtx('SBY');
await page.goto(base + '/pesanan-pembelian'); await page.waitForSelector(`[data-po="${poNo}"]`); await page.click(`[data-po="${poNo}"]`);
await page.waitForSelector('[data-action=po-to-invoice]'); await page.click('[data-action=po-to-invoice]'); await page.waitForSelector('#ai-total');
await page.fill('#ai-total', '8000000'); await page.fill('#ai-no', 'KCS/UJI/01'); await page.click('[data-action=save-po-invoice]');
await page.waitForSelector('.modal [role=alert]');
ok((await page.locator('.modal [role=alert]').innerText()).includes('tidak sama'), 'nilai tagihan pemasok berbeda ditolak (cocok tiga arah)');
await page.fill('#ai-total', String(Math.round((200 * 35000 + 500000) * 1.11))); await page.click('[data-action=save-po-invoice]');
await page.waitForURL(/\/tagihan-pemasok\?id=/); await page.waitForSelector('.drawer [data-open]');
const apNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
ok(/^APV-2026-\d{4}$/.test(apNo) && (await page.locator('.drawer .drawer-eyebrow').innerText()).includes('Cocok 3 arah'), 'draf tagihan dari PO, cocok tiga arah', apNo);
ok(await page.locator('[data-action=post-ap-invoice]').count() === 0, 'pembuat tagihan tidak ditawari tombol posting (SoD)'); await shot('54-tagihan-draf');
await page.keyboard.press('Escape'); await logout(); await login('andi@knm.co.id'); await salesCtx('SBY');
await page.goto(base + '/tagihan-pemasok'); await page.waitForSelector(`[data-ap-invoice="${apNo}"]`); await page.click(`[data-ap-invoice="${apNo}"]`);
await page.waitForSelector('[data-action=post-ap-invoice]'); await page.click('[data-action=post-ap-invoice]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Belum dibayar'), null, { timeout: 15000 });
ok(await page.locator('[data-table=ap-journals] tbody tr').count() === 1, 'tagihan diposting: jurnal utang tampil di laci'); await shot('55-tagihan-posting');
await page.keyboard.press('Escape'); await logout(); await login('sari@knm.co.id'); await salesCtx('SBY');
await page.goto(base + '/tagihan-pemasok'); await page.waitForSelector(`[data-ap-invoice="${apNo}"]`); await page.click(`[data-ap-invoice="${apNo}"]`);
await page.waitForSelector('[data-action=new-payment]'); await page.click('[data-action=new-payment]'); await page.waitForSelector('#pay-amount');
ok((await page.locator('[data-approvals-hint]').innerText()).includes('1 penyetuju'), 'formulir menjelaskan jumlah penyetuju yang diperlukan');
await page.fill('#pay-ref', 'TRF-UJI-SBY'); await page.click('[data-action=save-payment]');
await page.waitForSelector('[data-table=ap-payments] tbody tr');
ok((await page.locator('[data-table=ap-payments]').innerText()).includes('Menunggu'), 'pembayaran diajukan, menunggu persetujuan'); await shot('56-ajukan-bayar');
await page.keyboard.press('Escape'); await logout(); await login('osmond@knm.co.id');
await page.goto(base + '/pembayaran'); await page.waitForSelector('[data-chip=menunggu]'); await page.click('[data-chip=menunggu]');
await page.click('[data-table=payments] tbody tr[data-row] >> nth=0'); await page.waitForSelector('[data-decision]');
ok(await page.locator('[data-action=approve-payment]').count() === 1, 'manajer melihat tombol setujui pembayaran'); await shot('57-setujui-bayar');
await page.click('[data-action=approve-payment]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Disetujui'), null, { timeout: 15000 });
ok((await page.locator('[data-approvals]').innerText()).includes('Osmond Pratama'), 'persetujuan tercatat dengan nama penyetuju');
await page.keyboard.press('Escape'); await logout(); await login('sari@knm.co.id'); await salesCtx('SBY');
await page.goto(base + '/pembayaran'); await page.waitForSelector('[data-chip=disetujui]'); await page.click('[data-chip=disetujui]');
await page.click('[data-table=payments] tbody tr[data-row] >> nth=0'); await page.waitForSelector('[data-action=execute-payment]');
await page.click('[data-action=execute-payment]'); await page.waitForSelector('#ex-date'); await page.click('[data-action=confirm-execute]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Dibayar'), null, { timeout: 15000 });
ok(true, 'pembayaran dieksekusi setelah disetujui'); await shot('58-dibayar');
await page.keyboard.press('Escape');
await page.goto(base + '/hutang'); await page.waitForSelector('[data-aging]');
ok((await page.locator('[data-aging]').innerText()).includes('Cocok'), 'hutang usaha cocok dengan buku besar'); await shot('59-hutang');
await page.goto(base + '/integrasi'); await page.waitForSelector('.pill');
ok(await page.locator('.pill[data-tone=danger]').count() === 0, 'integrasi cocok setelah siklus pembelian (hutang, GRNI, persediaan, kas)');
await logout(); await login('osmond@knm.co.id');
await page.goto(base + '/pemasok'); await page.waitForSelector('[data-table=suppliers] tbody tr[data-row]');
await page.click('[data-action=new-supplier]'); await page.fill('#sp-name', `PT Pemasok Web ${Date.now().toString(36)}`); await page.fill('#sp-category', 'Jasa');
await page.fill('#sp-bank', 'BCA'); await page.fill('#sp-last4', '4321'); await page.click('[data-action=save-supplier]'); await page.waitForTimeout(600);
await page.selectOption('[aria-label="Saring status"]', 'rekening'); await page.waitForTimeout(200);
await page.click('[data-table=suppliers] tbody tr[data-row] >> nth=0'); await page.waitForSelector('[data-bank-pending]');
ok(await page.locator('[data-action=approve-bank]').count() === 0, 'pengusul rekening tidak ditawari tombol setujui (K-25)'); await shot('60-pemasok');
await page.keyboard.press('Escape');
await logout(); await login('admin@knm.co.id');
const navA = await page.locator('.rail-link-text').allInnerTexts();
ok(['Pesanan Pembelian', 'Tagihan Pemasok', 'Pembayaran', 'Faktur', 'Pesanan Penjualan', 'Jurnal Umum', 'Pengguna', 'Peran & Izin'].every((x) => navA.includes(x)), 'admin melihat semua modul (penjualan, pembelian, keuangan, sistem)', navA);
await page.goto(base + '/tagihan-pemasok'); await page.waitForSelector('[data-table=ap-invoices] tbody tr[data-row]');
ok(await page.locator('[data-action=new-ap-invoice]').count() === 1, 'admin dapat menginput tagihan pemasok'); await shot('61-admin-pembelian');

console.log('Pengadaan: permintaan pembelian → RFQ → PO');
await logout(); await login('fitri@knm.co.id');
await page.goto(base + '/permintaan-pembelian'); await page.waitForSelector('[data-table=requisitions] tbody tr[data-row]');
ok(await page.locator('[data-table=requisitions] tbody tr[data-row]').count() >= 1, 'daftar permintaan pembelian dimuat'); await shot('62-pr');
await page.click('[data-action=new-pr]'); await page.waitForSelector('[data-line] [data-field=product] option >> text=BRG-3390', { state: 'attached' });
await page.fill('[data-field=department]', 'Gudang'); await page.fill('[data-field=description]', 'Kabel NYY stok pengaman uji web'); await page.selectOption('[data-field=priority]', 'tinggi');
await page.selectOption('[data-line] [data-field=product]', await page.locator('[data-line] [data-field=product] option', { hasText: 'BRG-3390' }).first().getAttribute('value'));
await page.fill('[data-line] [data-field=qty]', '50'); await page.fill('[data-line] [data-field=price]', '35000');
ok((await page.locator('[data-total]').innerText()).replace(/\D/g, '') === '1750000', 'perkiraan nilai PR (sebelum PPN)', await page.locator('[data-total]').innerText());
await shot('63-pr-baru'); await page.click('[data-action=submit-pr]');
await page.waitForSelector('.drawer [data-table=pr-lines]'); await page.waitForTimeout(300);
const prNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
ok(/^PR-2026-\d{4}$/.test(prNo) && (await page.locator('.drawer [data-decision]').innerText()).includes('SLA'), 'PR diajukan; SLA prioritas tinggi tampil', prNo);
ok(await page.locator('[data-action=approve-pr]').count() === 0, 'pemohon tidak ditawari tombol setujui');
await page.keyboard.press('Escape'); await logout(); await login('osmond@knm.co.id');
await page.goto(base + '/permintaan-pembelian'); await page.waitForSelector(`[data-pr="${prNo}"]`); await page.click(`[data-pr="${prNo}"]`);
await page.waitForSelector('[data-action=approve-pr]'); await page.click('[data-action=approve-pr]');
await page.waitForSelector('[data-action=pr-to-rfq]'); ok(true, 'manajer menyetujui PR; tombol RFQ / PO langsung tersedia');
await page.click('[data-action=pr-to-rfq]'); await page.waitForSelector('[data-field=rfq-supplier]');
await page.locator('[data-field=rfq-supplier]').nth(0).check(); await page.locator('[data-field=rfq-supplier]').nth(1).check();
ok((await page.locator('[data-rfq-count]').innerText()).startsWith('2'), 'dua pemasok dipilih untuk RFQ'); await shot('64-rfq-baru');
await page.click('[data-action=save-rfq]'); await page.waitForURL(/\/rfq\?id=/); await page.waitForSelector('.drawer [data-table=rfq-quotes] tbody tr');
const qCodes = await page.locator('[data-table=rfq-quotes] tbody tr').evaluateAll((rows) => rows.map((r) => r.getAttribute('data-quote')));
const quote = async (code, price, lead) => {
  await page.click(`[data-quote="${code}"] [data-action=record-quote]`); await page.waitForSelector('[data-field=quote-price]');
  await page.fill('[data-field=quote-price]', String(price)); await page.fill('[data-field=lead]', String(lead)); await page.click('[data-action=save-quote]');
  await page.waitForFunction((c) => document.querySelector(`[data-quote="${c}"]`)?.textContent?.includes('Penawaran masuk'), code, { timeout: 15000 });
};
await quote(qCodes[0], 36000, 3); await quote(qCodes[1], 34000, 7);
ok((await page.locator(`[data-quote="${qCodes[1]}"]`).innerText()).includes('Terbaik'), 'penawaran terendah ditandai harga terbaik'); await shot('65-rfq-banding');
await page.click(`[data-quote="${qCodes[1]}"] [data-action=award]`); await page.waitForSelector('[data-action=confirm-award]'); await page.click('[data-action=confirm-award]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Dipesan'), null, { timeout: 15000 });
ok(await page.locator('.drawer [data-link=po]').count() === 1, 'pemenang dipilih → PO dibuat & tertaut'); await shot('66-rfq-pemenang');
await page.click('.drawer [data-link=po]'); await page.waitForURL(/\/pesanan-pembelian\?id=/); await page.waitForSelector('.drawer [data-po-source]');
ok((await page.locator('.drawer [data-po-source]').innerText()).includes(prNo) && (await page.locator('.drawer [data-table=po-lines]').innerText()).includes('34.000'), 'PO menampilkan asal PR/RFQ dan harga pemenang'); await shot('67-po-dari-rfq');
await page.keyboard.press('Escape');

console.log('Anggaran & proyek');
await logout(); await login('sari@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/anggaran'); await page.waitForSelector('[data-table=budget-lines] tbody tr[data-row]');
ok(await page.locator('[data-table=budget-lines] tbody tr[data-row]').count() > 0, 'anggaran vs realisasi per akun dimuat'); await shot('68-anggaran');
await page.locator('[data-table=budget-lines] tbody tr[data-row]').first().click(); await page.waitForSelector('[data-table=budget-months] tbody tr');
ok(await page.locator('[data-table=budget-months] tbody tr').count() === 12, 'rincian 12 bulan anggaran vs realisasi'); await page.keyboard.press('Escape');
await page.click('[data-tab=kelompok]'); await page.waitForSelector('[data-table=budget-groups] tbody tr');
ok(true, 'rekap per kelompok akun'); await page.click('[data-tab=akun]');
await page.click('[data-action=new-budget]'); await page.waitForSelector('#bg-branch');
await page.selectOption('#bg-branch', 'CKR'); await page.fill('[data-field=fiscal-year]', '2028'); await page.fill('[data-field=growth]', '5');
await page.click('[data-action=save-new-budget]');
await page.waitForFunction(() => document.querySelector('[data-field=budget]')?.selectedOptions?.[0]?.textContent?.includes('CKR · 2028') && document.querySelector('[data-budget-state]')?.textContent?.includes('Draf'), null, { timeout: 15000 });
ok((await page.locator('[data-table=budget-lines] tbody tr[data-row]').count()) > 0, 'anggaran baru CKR 2028 tersusun dari realisasi (draf)');
await page.click('[data-action=submit-budget]'); await page.waitForFunction(() => document.querySelector('[data-budget-state]')?.textContent?.includes('Menunggu'), null, { timeout: 15000 });
ok(await page.locator('[data-action=approve-budget]').count() === 0, 'penyusun tidak ditawari tombol setujui anggaran'); await shot('69-anggaran-ajukan');
await logout(); await login('andi@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/anggaran'); await page.waitForSelector('[data-field=budget] option', { state: 'attached' });
await page.selectOption('[data-field=budget]', { label: (await page.locator('[data-field=budget] option', { hasText: 'CKR · 2028' }).innerText()).trim() });
await page.waitForSelector('[data-action=approve-budget]'); await page.click('[data-action=approve-budget]');
await page.waitForFunction(() => !document.querySelector('[data-budget-state]'), null, { timeout: 15000 });
ok(true, 'akuntan senior menyetujui anggaran');
await logout(); await login('osmond@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/proyek'); await page.waitForSelector('[data-table=projects] tbody tr[data-row]');
ok(await page.locator('[data-table=projects] tbody tr[data-row]').count() >= 2, 'daftar proyek dengan kesehatan & kemajuan'); await shot('70-proyek');
await page.click('[data-action=new-project]'); await page.waitForSelector('[data-field=project-name]');
await page.fill('[data-field=project-name]', 'Proyek uji web'); await page.fill('[data-field=project-start]', '2026-10-01'); await page.fill('[data-field=project-end]', '2026-12-31');
await page.fill('[data-field=project-budget]', '50000000'); await page.selectOption('[data-field=project-status]', 'berjalan');
await page.click('[data-action=add-task]'); await page.fill('[data-field=task-name]', 'Instalasi'); await page.fill('[data-field=task-progress]', '40');
await page.click('[data-action=save-project]'); await page.waitForSelector('.drawer [data-gantt]');
ok((await page.locator('.drawer .drawer-eyebrow .code').innerText()).startsWith('PRJ-2026-') && (await page.locator('.drawer [data-task="Instalasi"]').count()) === 1, 'proyek dibuat; jadwal tugas tampil (Gantt)'); await shot('71-proyek-detail');
await page.keyboard.press('Escape');
await page.locator('[data-table=projects] tbody tr[data-row]', { hasText: 'Proyek uji e2e' }).first().click(); await page.waitForSelector('.drawer [data-table=project-entries]');
ok((await page.locator('.drawer [data-project-actual]').innerText()).replace(/\D/g, '').length > 0, 'biaya aktual proyek dari buku besar tampil'); await page.keyboard.press('Escape');

console.log('Kas & bank: transfer, rekonsiliasi, setoran pajak');
const API = 'http://localhost:3000/api/v1';
const apiToken = async (email) => (await (await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-forwarded-for': `10.77.${Date.now() % 200}.${(ipSeq += 1) % 250 + 1}` }, body: JSON.stringify({ email, password: PW }) })).json()).access_token;
const apiGet = async (tok, path, branch = 'ALL', period = '2026-09') => (await fetch(`${API}${path}`, { headers: { authorization: `Bearer ${tok}`, 'x-branch-id': branch, 'x-period-id': period } })).json();
await logout(); await login('sari@knm.co.id'); await salesCtx('CKR');
await page.goto(base + '/transfer-kas'); await page.waitForSelector('[data-action=new-transfer]');
await page.click('[data-action=new-transfer]'); await page.waitForSelector('#tr-from option:nth-child(2)', { state: 'attached' });
const banksAll = (await apiGet(await apiToken('andi@knm.co.id'), '/ledger/bank-accounts')).accounts;
const kasCkr = banksAll.find((b) => b.branchCode === 'CKR' && b.bankName === 'Kas' && b.status === 'aktif');
const bankCkr = banksAll.find((b) => b.branchCode === 'CKR' && b.bankName !== 'Kas' && b.status === 'aktif');
await page.selectOption('#tr-from', bankCkr.code); await page.selectOption('#tr-to', kasCkr.code);
await page.fill('#tr-amount', '1000000'); await page.fill('#tr-date', '2026-09-27'); await page.fill('#tr-ref', 'Isi kas kecil uji web');
ok((await page.locator('[data-transfer-hint]').innerText()).includes('Satu cabang'), 'formulir transfer menjelaskan jenis jurnal');
await shot('70-transfer-baru'); await page.click('[data-action=save-transfer]');
await page.waitForSelector('.drawer [data-decision]'); await page.waitForTimeout(300);
const trNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
ok(/^TRF-2026-\d{4}$/.test(trNo) && await page.locator('[data-action=approve-transfer]').count() === 0, 'transfer diajukan; pengaju tidak ditawari tombol setujui', trNo);
await page.keyboard.press('Escape'); await logout(); await login('andi@knm.co.id');
await page.goto(base + '/transfer-kas'); await page.waitForSelector(`[data-transfer="${trNo}"]`); await page.click(`[data-transfer="${trNo}"]`);
await page.waitForSelector('[data-action=approve-transfer]'); await page.click('[data-action=approve-transfer]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Diposting'), null, { timeout: 15000 });
ok(await page.locator('[data-table=transfer-journals] tbody tr').count() === 1, 'akuntan menyetujui: jurnal transfer tampil'); await shot('71-transfer-diposting');
await page.keyboard.press('Escape');

/* Rekonsiliasi: CSV kas kecil CKR tanggal 27/09 */
const andiTok = await apiToken('andi@knm.co.id');
const kasNow = (await apiGet(andiTok, '/ledger/bank-accounts')).accounts.find((b) => b.code === kasCkr.code);
const card = await apiGet(andiTok, `/ledger/accounts/${kasNow.glAccountCode}/card?bank=${kasCkr.code}`, 'CKR');
const kasBefore = card.opening + card.lines.filter((l) => l.date < '2026-09-27').reduce((t, l) => t + l.debit - l.credit, 0);
const dayLines = card.lines.filter((l) => l.date === '2026-09-27');
const f = (n) => n.toLocaleString('id-ID') + ',00';
let runBal = kasBefore;
const csv = ['Tanggal;Keterangan;Referensi;Debit;Kredit;Saldo', `27/09/2026;SALDO AWAL;;;;"${f(runBal)}"`];
for (const l of dayLines) { runBal += l.debit - l.credit; csv.push(`27/09/2026;${l.description.replace(/;/g, ',')};${l.ref ?? ''};${l.credit ? `"${f(l.credit)}"` : ''};${l.debit ? `"${f(l.debit)}"` : ''};"${f(runBal)}"`); }
runBal -= 2500; csv.push(`27/09/2026;BIAYA MATERAI;;"2.500,00";;"${f(runBal)}"`);
await logout(); await login('sari@knm.co.id'); await salesCtx('CKR');
await page.goto(base + '/rekonsiliasi-bank'); await page.waitForSelector('[data-table=recon-banks]'); await shot('72-rekonsiliasi');
await page.click('[data-action=import-statement]'); await page.waitForSelector('#st-bank');
await page.selectOption('#st-bank', kasCkr.code);
await page.setInputFiles('[data-field=statement-file]', { name: 'kas-kecil-ckr.csv', mimeType: 'text/csv', buffer: Buffer.from(csv.join('\n')) });
await page.waitForSelector('.modal .field-hint:has-text("kas-kecil-ckr.csv")');
await page.click('[data-action=save-import]'); await page.waitForURL(/\/rekonsiliasi-bank\/[0-9a-f-]{36}$/); await page.waitForSelector('[data-table=statement-lines]');
const stUrl = page.url();
ok(await page.locator('[data-line-status=cocok]').count() === dayLines.length && await page.locator('[data-line-status=belum]').count() === 1, 'mutasi CSV diimpor; transfer cocok otomatis, biaya materai terbuka', [dayLines.length]);
ok(await page.locator('[data-action=finalize-recon]').count() === 0, 'pengimpor tidak ditawari tombol finalisasi'); await shot('73-rekonsiliasi-detail');
await page.click('[data-line-status=belum] [data-action=ignore-line]'); await page.fill('#reason-input', 'materai ditanggung bank, dikoreksi bulan depan'); await page.click('[data-action=confirm-reason]');
await page.waitForSelector('[data-line-status=diabaikan]');
ok((await page.locator('[data-recon-summary]').innerText()).includes('Saldo buku disesuaikan'), 'ringkasan rekonsiliasi tampil');
await logout(); await login('andi@knm.co.id');
await page.goto(stUrl); await page.waitForSelector('[data-action=finalize-recon]');
ok(!(await page.locator('[data-action=finalize-recon]').isDisabled()), 'rekonsiliasi seimbang: tombol finalisasi aktif bagi akuntan');
await page.click('[data-action=finalize-recon]'); await page.waitForSelector('[data-finalized]');
ok(true, 'rekonsiliasi difinalisasi oleh orang lain'); await shot('74-rekonsiliasi-selesai');

/* Setoran pajak */
await page.goto(base + '/setoran-pajak'); await page.waitForSelector('[data-table=ppn-branches]');
ok(await page.locator('[data-table=ppn-branches] tbody tr').count() >= 1, 'setoran PPN: saldo per cabang tampil'); await shot('75-setoran-pajak');
if (await page.locator('[data-action=open-existing-tax]').count()) {
  await page.click('[data-action=open-existing-tax]'); await page.waitForSelector('[data-table=tax-journals]');
  ok(await page.locator('[data-table=tax-journals] tbody tr').count() >= 2, 'setoran masa berjalan: jurnal per cabang tampil'); await page.keyboard.press('Escape');
}
await logout(); await login('admin@knm.co.id');

console.log('Persediaan: opname, transfer stok, kartu stok');
const stockNow = async () => (await apiGet(await apiToken('andi@knm.co.id'), '/inventory/stock')).items;
const peti = (await stockNow()).find((i) => i.sku === 'BRG-6110' && i.warehouse === 'Surabaya');
await logout(); await login('fitri@knm.co.id');
await page.goto(base + '/penyesuaian-stok'); await page.waitForSelector('[data-action=new-adjustment]'); await shot('80-penyesuaian-stok');
await page.click('[data-action=new-adjustment]'); await page.waitForSelector('#adj-wh option[value="Surabaya"]', { state: 'attached' });
await page.selectOption('#adj-wh', 'Surabaya'); await page.fill('#adj-date', '2026-09-28'); await page.fill('#adj-notes', 'Opname uji web');
await page.selectOption('.modal [data-line] [data-field=sku]', 'BRG-6110'); await page.fill('.modal [data-line] [data-field=counted]', String(peti.onHand - 1));
ok((await page.locator('[data-estimate]').innerText()).includes(peti.avgCost.toLocaleString('id-ID')), 'formulir opname menampilkan estimasi nilai selisih', await page.locator('[data-estimate]').innerText());
await shot('81-opname-baru'); await page.click('[data-action=save-adjustment]');
await page.waitForSelector('.drawer [data-decision]'); await page.waitForTimeout(300);
const adjNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
ok(/^ADJ-2026-\d{4}$/.test(adjNo) && await page.locator('[data-action=approve-adjustment]').count() === 0, 'staf gudang mencatat opname; tidak dapat menyetujui', adjNo);
await page.keyboard.press('Escape'); await logout(); await login('andi@knm.co.id');
await page.goto(base + '/penyesuaian-stok'); await page.waitForSelector(`[data-adjustment="${adjNo}"]`); await page.click(`[data-adjustment="${adjNo}"]`);
await page.waitForSelector('[data-action=approve-adjustment]'); await page.click('[data-action=approve-adjustment]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Diposting'), null, { timeout: 15000 });
ok(await page.locator('[data-table=adjustment-journals] tbody tr').count() === 1 && (await page.locator('[data-adj-total]').innerText()).includes(peti.avgCost.toLocaleString('id-ID')), 'akuntan memposting opname: jurnal selisih persediaan tampil');
await shot('82-opname-diposting'); await page.keyboard.press('Escape');

await logout(); await login('admin@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/transfer-stok'); await page.waitForSelector('[data-action=new-stock-transfer]');
await page.click('[data-action=new-stock-transfer]'); await page.waitForSelector('#st-from option[value="Cikarang"]', { state: 'attached' });
await page.selectOption('#st-from', 'Cikarang'); await page.selectOption('#st-to', 'Surabaya'); await page.fill('#st-date', '2026-09-28');
await page.selectOption('.modal [data-line] [data-field=sku]', 'BRG-1042'); await page.fill('.modal [data-line] [data-field=qty]', '2');
ok((await page.locator('[data-stock-transfer-hint]').innerText()).includes('dalam perjalanan'), 'formulir menjelaskan transfer antar cabang');
await shot('83-transfer-stok-baru'); await page.click('[data-action=save-stock-transfer]');
await page.waitForSelector('[data-action=ship-transfer]');
const trsNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
await page.click('[data-action=ship-transfer]'); await page.waitForSelector('.drawer [data-transit]');
ok(await page.locator('[data-table=stock-transfer-journals] tbody tr').count() === 2, 'kirim antar cabang: jurnal di cabang asal & tujuan', trsNo); await shot('84-transfer-dalam-perjalanan');
await page.keyboard.press('Escape'); await logout(); await login('fitri@knm.co.id');
await page.goto(base + '/transfer-stok'); await page.waitForSelector(`[data-stock-transfer="${trsNo}"]`); await page.click(`[data-stock-transfer="${trsNo}"]`);
await page.waitForSelector('[data-action=receive-transfer]'); await page.fill('#rcv-date', '2026-09-29'); await page.click('[data-action=receive-transfer]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Diterima'), null, { timeout: 15000 });
ok(await page.locator('[data-table=stock-transfer-journals] tbody tr').count() === 3, 'gudang Surabaya menerima: jurnal penerimaan ditambahkan'); await shot('85-transfer-diterima');
await page.keyboard.press('Escape');
await page.goto(base + '/stok'); await page.waitForSelector('[data-sku="BRG-1042"][data-warehouse="Surabaya"]');
await page.click('[data-sku="BRG-1042"][data-warehouse="Surabaya"]'); await page.waitForSelector('[data-table=stock-card] [data-move=transfer_in]');
ok((await page.locator('[data-closing]').innerText()).trim() === '2', 'kartu stok Surabaya: transfer masuk dengan saldo berjalan'); await shot('86-kartu-stok');
await page.keyboard.press('Escape');
await logout(); await login('andi@knm.co.id');
await page.goto(base + '/integrasi'); await page.waitForSelector('.pill');
ok(await page.locator('.pill[data-tone=danger]').count() === 0, 'rekonsiliasi (termasuk persediaan & barang dalam perjalanan) tetap cocok');
await page.goto(base + '/stok'); await page.waitForSelector('[data-table=warehouses] tbody tr'); await shot('87-stok');
await logout(); await login('admin@knm.co.id');

console.log('Produksi: BOM & perintah kerja');
await salesCtx('ALL');
await page.goto(base + '/bom'); await page.waitForSelector('[data-bom="BOM-BRK-B"]');
ok(await page.locator('[data-table=boms] tbody tr[data-bom]').count() >= 2, 'daftar BOM dengan estimasi biaya bahan'); await shot('90-bom');
await page.goto(base + '/perintah-kerja'); await page.waitForSelector('[data-board]'); await shot('91-papan-produksi');
await page.click('[data-action=new-wo]'); await page.waitForSelector('#wo-bom option:nth-child(2)', { state: 'attached' });
const bomId = await page.locator('#wo-bom option', { hasText: 'BOM-BRK-B' }).getAttribute('value');
await page.selectOption('#wo-bom', bomId); await page.selectOption('#wo-wh', 'Cikarang'); await page.fill('#wo-qty', '40');
await page.fill('#wo-date', '2026-09-28'); await page.fill('#wo-due', '2026-09-30'); await page.fill('#wo-line', 'Lini 2 — Pres'); await page.fill('#wo-pic', 'Dedi Kurnia');
await page.waitForSelector('[data-table=wo-preview] tbody tr');
ok(await page.locator('[data-table=wo-preview] tbody tr').count() === 3, 'pratinjau kebutuhan bahan dari BOM'); await shot('92-wo-baru');
await page.click('[data-action=save-wo]'); await page.waitForSelector('[data-action=issue-materials]');
const woNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
await page.click('[data-action=issue-materials]'); await page.waitForSelector('#iss-date'); await page.fill('#iss-date', '2026-09-28');
await page.click('[data-action=save-issue]'); await page.waitForFunction(() => document.querySelector('.drawer [data-wip]')?.textContent?.trim() !== 'Rp 0', null, { timeout: 15000 });
ok(await page.locator('[data-table=wo-journals] tbody tr').count() === 1, 'bahan dikeluarkan: jurnal WIP tampil', woNo);
await page.click('[data-action=submit-qc]'); await page.waitForSelector('#qc-good'); await page.fill('#qc-reject', '1'); await page.fill('#qc-good', '39'); await page.click('[data-action=save-qc]');
await page.waitForSelector('.drawer [data-qc]');
ok(await page.locator('[data-action=complete-wo]').count() === 0, 'pelapor hasil tidak ditawari tombol lolos QC'); await shot('93-wo-qc');
await page.keyboard.press('Escape'); await logout(); await login('osmond@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/perintah-kerja'); await page.waitForSelector(`[data-wo="${woNo}"]`); await page.click(`[data-wo="${woNo}"]`);
await page.waitForSelector('[data-action=complete-wo]'); await page.fill('#wo-done-date', '2026-09-29'); await page.click('[data-action=complete-wo]');
await page.waitForFunction(() => document.querySelector('.drawer .drawer-eyebrow .pill')?.textContent?.includes('Selesai'), null, { timeout: 15000 });
ok(await page.locator('[data-table=wo-journals] tbody tr').count() === 2 && (await page.locator('.drawer [data-wip]').innerText()).trim() === 'Rp 0', 'manajer meloloskan QC: barang jadi diposting, WIP nol');
await shot('94-wo-selesai'); await page.keyboard.press('Escape');
await page.waitForSelector(`[data-col=selesai] [data-wo="${woNo}"]`);
ok(true, 'kartu pindah ke kolom Selesai');
await logout(); await login('admin@knm.co.id');

console.log('POS / kasir');
await salesCtx('ALL');
await page.goto(base + '/kasir'); await page.waitForSelector('[data-action=open-shift]');
await page.click('[data-action=open-shift]'); await page.waitForSelector('#sh-wh option[value="Cikarang"]', { state: 'attached' });
await page.selectOption('#sh-wh', 'Cikarang'); await page.fill('#sh-date', '2026-09-30'); await page.waitForTimeout(200);
ok(await page.locator('#sh-cash').inputValue() !== '', 'kas laci terpilih otomatis untuk toko');
await page.click('[data-action=save-open-shift]'); await page.waitForSelector('[data-register]');
await page.waitForSelector('[data-product="BRG-1108"]'); await page.click('[data-product="BRG-1108"]'); await page.click('[data-product="BRG-1108"]');
ok((await page.locator('[data-cart="BRG-1108"] input').inputValue()) === '2', 'barang masuk keranjang (qty bertambah)');
const posTotal = (await page.locator('[data-pos-total]').innerText()).trim();
await page.fill('#pos-tendered', '2000000'); await page.waitForSelector('[data-change]'); await shot('95-kasir');
await page.click('[data-action=pay]');
ok(await page.waitForFunction(() => document.querySelector('[data-register] .card-note')?.textContent?.includes('1 transaksi'), null, { timeout: 15000 }).then(() => true, () => false), 'transaksi tunai tercatat', posTotal);
await page.click('[data-action=close-shift]'); await page.waitForSelector('#cl-counted');
ok((await page.locator('[data-close-diff]').innerText()).includes('Rp 0'), 'hitung kas default = kas seharusnya');
await page.click('[data-action=save-close-shift]'); await page.waitForSelector('.drawer [data-post-panel]');
ok(await page.locator('[data-action=post-shift]').count() === 0, 'kasir tidak ditawari tombol posting'); await shot('96-shift-ditutup');
const shNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
await page.keyboard.press('Escape'); await logout(); await login('osmond@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/kasir'); await page.waitForSelector(`[data-shift="${shNo}"]`); await page.click(`[data-shift="${shNo}"]`);
await page.waitForSelector('[data-action=post-shift]'); await page.click('[data-action=post-shift]');
await page.waitForSelector('[data-table=pos-journals] tbody tr');
ok((await page.locator('.drawer .drawer-eyebrow .pill').innerText()).includes('Diposting'), 'supervisor memposting shift: jurnal tampil'); await shot('97-shift-diposting');
await page.keyboard.press('Escape');
await page.goto(base + '/integrasi'); await page.waitForSelector('.pill');
ok(await page.locator('.pill[data-tone=danger]').count() === 0, 'rekonsiliasi tetap cocok setelah POS & produksi');
await logout(); await login('admin@knm.co.id');

console.log('Aset tetap & pemeliharaan');
await logout(); await login('andi@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/aset'); await page.waitForSelector('[data-depr-branch="CKR"]');
ok((await page.locator('[data-depr-branch="CKR"]').innerText()).includes('Diposting'), 'penyusutan September tercatat diposting per cabang'); await shot('98-aset');
await page.click('[data-asset="AST-0014"]'); await page.waitForSelector('[data-table=asset-depr] tbody tr');
ok(await page.locator('[data-action=dispose-asset]').count() === 1, 'akuntan dapat melepas aset dari laci'); await shot('99-aset-detail');
await page.keyboard.press('Escape');
await logout(); await login('sari@knm.co.id'); await salesCtx('CKR');
await page.goto(base + '/pemeliharaan'); await page.waitForSelector('[data-action=new-maintenance]');
await page.click('[data-action=new-maintenance]'); await page.waitForSelector('#mn-asset option', { state: 'attached' });
const pressId = await page.locator('#mn-asset option', { hasText: 'AST-0022' }).getAttribute('value');
await page.selectOption('#mn-asset', pressId); await page.fill('#mn-date', '2026-09-29'); await page.fill('#mn-desc', 'Ganti filter oli hidrolik'); await page.fill('#mn-est', '1500000');
await page.click('[data-action=save-maintenance]'); await page.waitForSelector('[data-action=complete-maintenance]');
await page.click('[data-action=complete-maintenance]'); await page.waitForSelector('#mc-cost'); await page.fill('#mc-date', '2026-09-29');
await page.click('[data-action=save-complete-maintenance]'); await page.waitForSelector('[data-table=mnt-journals] tbody tr');
ok((await page.locator('[data-mnt-total]').innerText()).includes('1.500.000'), 'pemeliharaan selesai: biaya dijurnal'); await shot('100-pemeliharaan');
await page.keyboard.press('Escape');
await logout(); await login('admin@knm.co.id');

console.log('SDM & penggajian');
await salesCtx('ALL');
await page.goto(base + '/karyawan'); await page.waitForSelector('[data-table=employees] tbody tr[data-employee]');
await page.locator('[data-table=employees] tbody tr[data-employee]').first().click(); await page.waitForSelector('[data-nik]');
ok(/^\*{4}\d{4}$/.test((await page.locator('[data-nik]').innerText()).trim()), 'NIK tampil tersamar');
await page.click('[data-action=reveal]'); await page.waitForFunction(() => /^\d{16}$/.test(document.querySelector('[data-nik]')?.textContent?.trim() ?? ''), null, { timeout: 15000 });
ok(true, 'pemegang izin membuka NIK (dicatat)'); await shot('101-karyawan'); await page.keyboard.press('Escape');
await page.goto(base + '/kehadiran'); await page.fill('[data-field=att-date]', '2026-09-15'); await page.waitForTimeout(600);
await page.click('[data-action=fill-present]'); await page.waitForTimeout(800);
ok(await page.locator('[data-table=attendance] select[data-field=status]').count() > 5, 'kehadiran harian dapat diisi'); await shot('102-kehadiran');
await page.goto(base + '/penggajian'); await page.click('[data-action=new-payroll]'); await page.waitForSelector('#pr-branch');
await page.selectOption('#pr-branch', 'CKR'); await page.fill('#pr-period', '2026-09'); await page.click('[data-action=save-payroll]');
await page.waitForSelector('.drawer [data-run-draft]');
const runNo = (await page.locator('.drawer .drawer-eyebrow .code').innerText()).trim();
ok(await page.locator('[data-action=post-payroll]').count() === 0 && await page.locator('[data-table=run-slips] tbody tr').count() >= 5, 'daftar gaji CKR disusun; penyusun tidak ditawari posting', runNo);
await shot('103-daftar-gaji'); await page.keyboard.press('Escape');
await logout(); await login('andi@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/penggajian'); await page.waitForSelector(`[data-run="${runNo}"]`); await page.click(`[data-run="${runNo}"]`);
await page.waitForSelector('[data-action=post-payroll]'); await page.click('[data-action=post-payroll]');
await page.waitForSelector('[data-table=run-journals] tbody tr');
ok((await page.locator('.drawer .drawer-eyebrow .pill').innerText()).includes('Diposting'), 'akuntan memposting daftar gaji'); await page.keyboard.press('Escape');
await logout(); await login('sari@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/penggajian'); await page.waitForSelector('[data-table=payable] tbody tr[data-payslip]');
for (const cb of await page.locator('[data-table=payable] input[type=checkbox]').all()) await cb.check();
await page.click('[data-action=pay-payroll]'); await page.waitForSelector('#py-bank'); await page.fill('#py-date', '2026-09-30');
await page.click('[data-action=confirm-pay]'); await page.waitForFunction(() => !document.querySelector('[data-table=payable] tbody tr[data-payslip]'), null, { timeout: 15000 });
ok(await page.waitForFunction(() => document.querySelectorAll('[data-table=payroll-payments] tbody tr').length >= 2, null, { timeout: 15000 }).then(() => true, () => false), 'staf keuangan membayar seluruh utang gaji (lintas cabang)'); await shot('104-pembayaran-gaji');
await logout(); await login('andi@knm.co.id');
await page.goto(base + '/integrasi'); await page.waitForSelector('.pill');
ok(await page.locator('.pill[data-tone=danger]').count() === 0, 'rekonsiliasi cocok setelah aset & penggajian');
await logout(); await login('admin@knm.co.id');

console.log('Kotak persetujuan, dokumen, kepatuhan');
await logout(); await login('sari@knm.co.id'); await salesCtx('ALL');
await page.goto(base + '/dokumen'); await page.waitForSelector('[data-action=new-document]');
await page.click('[data-action=new-document]'); await page.waitForSelector('[data-field=doc-file]');
await page.setInputFiles('[data-field=doc-file]', { name: 'sop-penerimaan.txt', mimeType: 'text/plain', buffer: Buffer.from('SOP penerimaan barang v1\n') });
await page.fill('#dc-folder', 'Operasional / SOP'); await page.selectOption('#dc-type', 'SOP');
await page.click('[data-action=save-document]'); await page.waitForSelector('[data-table=doc-versions] tbody tr');
await page.setInputFiles('[data-field=new-version]', { name: 'sop-penerimaan-v2.txt', mimeType: 'text/plain', buffer: Buffer.from('SOP penerimaan barang v2\n') });
await page.waitForFunction(() => document.querySelectorAll('[data-table=doc-versions] tbody tr').length === 2, null, { timeout: 15000 });
const dlP = page.waitForEvent('download', { timeout: 15000 });
await page.locator('[data-action=download-version]').last().click();
const dl = await dlP;
ok(dl.suggestedFilename() === 'sop-penerimaan.txt', 'dokumen diunggah, versi baru, unduh versi lama', dl.suggestedFilename()); await shot('105-dokumen');
await page.keyboard.press('Escape');
await page.goto(base + '/transfer-kas'); await page.waitForSelector('[data-table=transfers] tbody tr[data-row]');
await page.locator('[data-table=transfers] tbody tr[data-row]').first().click(); await page.waitForSelector('[data-attachments]');
await page.setInputFiles('[data-attachments] [data-field=attachment]', { name: 'bukti-transfer.txt', mimeType: 'text/plain', buffer: Buffer.from('bukti transfer\n') });
await page.waitForFunction(() => document.querySelector('[data-attachments] .section-title')?.textContent?.includes('(1)'), null, { timeout: 15000 });
ok(true, 'lampiran diunggah dari laci transaksi'); await page.keyboard.press('Escape');
await logout(); await login('andi@knm.co.id');
ok(await page.locator('[data-inbox-bell]').count() === 1, 'lonceng kotak persetujuan tampil di bilah atas');
await page.goto(base + '/kotak-masuk'); await page.waitForSelector('.kpi-tile'); await page.waitForTimeout(500); await shot('106-kotak-persetujuan');
ok(true, 'halaman kotak persetujuan dirender');
await page.goto(base + '/kepatuhan'); await page.waitForSelector('[data-chain]');
ok((await page.locator('[data-chain]').innerText()).includes('Utuh') && await page.locator('[data-table=sod-users] tbody tr').count() >= 6, 'kepatuhan: rantai audit utuh, laporan SoD per pengguna'); await shot('107-kepatuhan');
await logout(); await login('admin@knm.co.id');

console.log('Pembatasan hak: staf gudang Surabaya');
await page.click('.topbar-user button'); await page.click('.user-menu .menu-item:has-text("Keluar")'); await page.waitForURL(/masuk/);
await page.goto(base + '/masuk'); await page.fill('#email', 'fitri@knm.co.id'); await page.fill('#password', PW); await page.click('button[type=submit]'); await page.waitForTimeout(1200);
const nav = await page.locator('.rail-link-text').allInnerTexts();
ok(!nav.includes('Neraca') && !nav.includes('Jurnal Umum') && !nav.includes('Asisten AI'), 'menu laporan, jurnal & asisten tersembunyi bagi staf gudang', nav);
ok(!(await page.locator('.contextbar').innerText()).includes('Semua cabang'), 'staf gudang tidak mendapat konteks semua cabang');
await shot('17-gudang');

const mob = await browser.newContext({ viewport: { width: 390, height: 844 } });
const mp = await mob.newPage();
await mp.goto(base + '/masuk'); await mp.fill('#email', 'andi@knm.co.id'); await mp.fill('#password', PW); await mp.click('button[type=submit]'); await mp.waitForURL(/dasbor/); await mp.waitForTimeout(800);
await mp.goto(base + '/laba-rugi'); await mp.waitForSelector('.report-stmt'); await mp.waitForTimeout(300);
const overflow = await mp.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
ok(overflow <= 1, 'tampilan sempit tanpa luapan horizontal', overflow); await mp.screenshot({ path: `${out}/18-mobile-laba-rugi.png` });
await mp.route('**/api/v1/assistant/status', (r) => r.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ enabled: true, model: 'claude-opus-5' }) }));
await mp.route('**/api/v1/assistant/chat', (r) => r.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ reply: REPLY, toolsUsed: [{ name: 'konsolidasi', ok: true }], usage: { inputTokens: 1, outputTokens: 1 }, model: 'claude-opus-5', stopReason: 'end_turn' }) }));
await mp.goto(base + '/asisten'); await mp.waitForSelector('.assistant-suggest .chip'); await mp.click('.assistant-suggest .chip >> nth=0'); await mp.waitForSelector('.md table'); await mp.waitForTimeout(300);
const overflowA = await mp.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
ok(overflowA <= 1, 'halaman asisten di ponsel tanpa luapan horizontal', overflowA); await mp.screenshot({ path: `${out}/20-mobile-asisten.png` });
await browser.close();
if (problems.length) { console.error(`GAGAL — ${problems.length} masalah:`); problems.forEach((p) => console.error('  · ' + p)); process.exit(1); }
console.log('LULUS — uji peramban aplikasi web');
